import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'alumniPage',
  title: 'Alumni page',
  type: 'document',
  groups: [
    { name: 'hero', title: '1. Hero' },
    { name: 'spotlights', title: '2. Alumni spotlights' },
    { name: 'about', title: '3. About the programme' },
    { name: 'comingSoon', title: '4. Coming soon callout' },
    { name: 'links', title: '5. Related links' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Page title',
      type: 'string',
      group: 'hero',
      initialValue: 'Alumni',
    }),
    defineField({
      name: 'kicker',
      title: 'Kicker',
      type: 'string',
      group: 'hero',
      initialValue: 'ALUMNI',
    }),
    defineField({
      name: 'headline',
      title: 'Headline',
      type: 'string',
      group: 'hero',
      initialValue: 'Where Morpeth artists go next',
    }),
    defineField({
      name: 'intro',
      title: 'Intro',
      type: 'text',
      rows: 4,
      group: 'hero',
      initialValue:
        'Former students of the Portman Gallery programme continue to make, exhibit and work in art and photography. This page celebrates their journeys and current practice.',
    }),
    defineField({
      name: 'spotlights',
      title: 'Alumni spotlights',
      description: 'Short profiles of former students - their journey since leaving Morpeth.',
      type: 'array',
      group: 'spotlights',
      validation: (rule) => rule.max(24),
      of: [
        {
          type: 'object',
          name: 'alumniSpotlight',
          fields: [
            defineField({
              name: 'image',
              title: 'Photo or artwork',
              type: 'image',
              options: { hotspot: true },
              fields: [defineField({ name: 'alt', title: 'Alt text', type: 'string' })],
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'name',
              title: 'Name',
              type: 'string',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'graduationYear',
              title: 'Year left Morpeth',
              type: 'number',
              validation: (rule) => rule.min(1980).max(2100),
            }),
            defineField({
              name: 'currentPursuit',
              title: 'Current pursuit',
              type: 'string',
              description: 'e.g. "Fine Art student, Goldsmiths" or "Freelance photographer"',
            }),
            defineField({
              name: 'quote',
              title: 'Quote or note',
              type: 'text',
              rows: 3,
            }),
            defineField({
              name: 'portfolioUrl',
              title: 'Portfolio / website link',
              type: 'url',
            }),
            defineField({
              name: 'instagramHandle',
              title: 'Instagram handle (optional)',
              type: 'string',
              description: 'Without the @ symbol.',
            }),
          ],
          preview: {
            select: {
              title: 'name',
              subtitle: 'currentPursuit',
              media: 'image',
            },
          },
        },
      ],
    }),
    defineField({
      name: 'aboutTitle',
      title: 'About section title',
      type: 'string',
      group: 'about',
      initialValue: 'About the alumni programme',
    }),
    defineField({
      name: 'aboutBody',
      title: 'About section body',
      description: 'Use a blank line to start a new paragraph.',
      type: 'text',
      rows: 6,
      group: 'about',
      initialValue:
        'Morpeth School has a long tradition of students going on to art school, photography degrees, and creative careers. The alumni section of the Portman Gallery is a space to celebrate that work - showing where the practice went after school.\n\nIf you studied Art or Photography at Morpeth and would like your work featured here, please get in touch via the Support page.',
    }),
    defineField({
      name: 'aboutCtaLabel',
      title: 'About section button label',
      type: 'string',
      group: 'about',
      initialValue: 'Get in touch',
    }),
    defineField({
      name: 'aboutCtaLink',
      title: 'About section button link',
      type: 'string',
      group: 'about',
      initialValue: '/support#contact',
    }),
    defineField({
      name: 'programmeListTitle',
      title: 'Outcomes list title',
      type: 'string',
      group: 'about',
      initialValue: 'Alumni featured here have gone on to:',
    }),
    defineField({
      name: 'programmeListItems',
      title: 'Outcomes list items',
      type: 'array',
      group: 'about',
      of: [{ type: 'string' }],
      validation: (rule) => rule.max(12),
      initialValue: [
        'BA Fine Art and Photography degrees',
        'Professional photography practices',
        'Graphic design and art direction',
        'Film, TV and media production',
        'Illustration and printmaking',
        'Arts education and community work',
      ],
    }),
    defineField({
      name: 'comingSoonTitle',
      title: 'Coming soon title',
      description: 'Shown above the alumni exhibitions grid when no alumni exhibitions are published yet.',
      type: 'string',
      group: 'comingSoon',
      initialValue: 'Coming soon',
    }),
    defineField({
      name: 'comingSoonBody',
      title: 'Coming soon body',
      type: 'text',
      rows: 3,
      group: 'comingSoon',
      initialValue:
        "Alumni exhibitions will appear here once published. If you're a former student who wants to share your work, please get in touch.",
    }),
    defineField({
      name: 'comingSoonPrimaryCtaLabel',
      title: 'Primary button label',
      type: 'string',
      group: 'comingSoon',
      initialValue: 'Submit your work',
    }),
    defineField({
      name: 'comingSoonPrimaryCtaLink',
      title: 'Primary button link',
      type: 'string',
      group: 'comingSoon',
      initialValue: '/support#contact',
    }),
    defineField({
      name: 'comingSoonSecondaryCtaLabel',
      title: 'Secondary button label',
      type: 'string',
      group: 'comingSoon',
      initialValue: 'Student work',
    }),
    defineField({
      name: 'comingSoonSecondaryCtaLink',
      title: 'Secondary button link',
      type: 'string',
      group: 'comingSoon',
      initialValue: '/student',
    }),
    defineField({
      name: 'relatedLinks',
      title: 'Related link cards',
      description: 'The three cards shown at the bottom of the page.',
      type: 'array',
      group: 'links',
      validation: (rule) => rule.max(6),
      of: [
        {
          type: 'object',
          name: 'relatedLinkCard',
          fields: [
            defineField({ name: 'title', title: 'Title', type: 'string', validation: (rule) => rule.required() }),
            defineField({ name: 'body', title: 'Body', type: 'text', rows: 3 }),
            defineField({ name: 'linkLabel', title: 'Link label', type: 'string', validation: (rule) => rule.required() }),
            defineField({ name: 'linkHref', title: 'Link URL or path', type: 'string', validation: (rule) => rule.required() }),
          ],
          preview: {
            select: { title: 'title', subtitle: 'linkLabel' },
          },
        },
      ],
      initialValue: [
        {
          title: 'Are you an alum?',
          body: "Share your practice, your path, and work made since Morpeth. We'd love to feature you.",
          linkLabel: 'Get in touch',
          linkHref: '/support#contact',
        },
        {
          title: 'Current students',
          body: 'See the work being made right now in the Portman Gallery by students across year groups.',
          linkLabel: 'Student work',
          linkHref: '/student',
        },
        {
          title: 'Guest artists',
          body: 'Visiting practitioners who have shown work and led sessions in the Portman Gallery.',
          linkLabel: 'Guest artists',
          linkHref: '/guest-artists',
        },
      ],
    }),
  ],
})
