import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'supportPage',
  title: 'Support page',
  type: 'document',
  groups: [
    { name: 'hero', title: '1. Hero' },
    { name: 'support', title: '2. Ways to support' },
    { name: 'prints', title: '3. Print sales' },
    { name: 'contact', title: '4. Contact' },
  ],
  initialValue: {
    pageTitle: 'SUPPORT THE GALLERY',
    pageIntro:
      "The Portman Gallery is Morpeth School's dedicated exhibition space. Support from families, alumni and partners helps us keep the programme active and ambitious.",
    heroKicker: 'Support',
    heroHeadline: 'Help the Portman Gallery grow',
    heroBody:
      'Sales of books and prints, donations and partnerships help us fund new shows, commission projects and provide opportunities for young people at Morpeth.',
    heroPanelColor: '#8CCFD6',
    primaryCtaLabel: 'Get in touch',
    primaryCtaLink: '#contact',
    secondaryCtaLabel: 'Browse prints',
    secondaryCtaLink: '#prints',
    supportStripTitle: 'Support pathways',
    supportPathways: [
      {
        title: 'Print purchases',
        description: 'Buy student and reference prints. Proceeds support production and exhibition costs.',
      },
      {
        title: 'Donations',
        description: 'One-off and recurring donations support materials, framing and public events.',
      },
      {
        title: 'Partnerships',
        description: 'Collaborate with us on workshops, talks and community-facing projects.',
      },
      {
        title: 'Volunteer time',
        description: 'Support installs, private views and documentation across the gallery year.',
      },
    ],
    printsSectionTitle: 'Prints and editions',
    printsSectionIntro:
      'A curated selection of work available to collect. Every purchase feeds directly back into the gallery programme.',
    featuredPrintKicker: 'Featured print',
    featuredPrintTitle: 'Collect work from the Portman Gallery programme',
    featuredPrintBody:
      'Explore limited runs and open editions connected to current and recent exhibitions.',
    featuredPrintCtaLabel: 'View all prints',
    featuredPrintCtaLink: '#contact',
    contactSectionTitle: 'Contact the gallery',
    contactSectionIntro:
      'Tell us what you are interested in and we will reply with options, prices and next steps.',
    contactEmail: 'info@morpeth.towerhamlets.sch.uk',
    contactPhone: '020 8981 0921',
    contactNote:
      'For school visits and group enquiries, include preferred dates and group size so we can plan with you.',
    formSubmitLabel: 'Send enquiry',
    formSuccessMessage: "Thanks - we'll get back to you shortly.",
  },
  fields: [
    defineField({
      name: 'pageTitle',
      title: 'Page title',
      type: 'string',
      group: 'hero',
      description: 'Main heading at the top of the page.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'pageIntro',
      title: 'Page intro',
      type: 'text',
      rows: 4,
      group: 'hero',
      description: 'Short introductory paragraph below the title.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      type: 'image',
      group: 'hero',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt text', type: 'string' })],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroPanelColor',
      title: 'Hero panel colour (hex)',
      type: 'string',
      group: 'hero',
      description: 'Example: #8CCFD6',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroKicker',
      title: 'Hero kicker',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'heroHeadline',
      title: 'Hero headline',
      type: 'string',
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'heroBody',
      title: 'Hero body',
      type: 'text',
      rows: 4,
      group: 'hero',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'primaryCtaLabel',
      title: 'Primary button label',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'primaryCtaLink',
      title: 'Primary button link',
      type: 'string',
      group: 'hero',
      description: 'Use #contact for on-page scroll, or a full URL.',
    }),
    defineField({
      name: 'secondaryCtaLabel',
      title: 'Secondary button label',
      type: 'string',
      group: 'hero',
    }),
    defineField({
      name: 'secondaryCtaLink',
      title: 'Secondary button link',
      type: 'string',
      group: 'hero',
      description: 'Use #prints for on-page scroll, or a full URL.',
    }),

    defineField({
      name: 'supportStripTitle',
      title: 'Support strip title',
      type: 'string',
      group: 'support',
      description: 'Small heading above the support pathway cards.',
    }),
    defineField({
      name: 'supportPathways',
      title: 'Support pathway cards',
      type: 'array',
      group: 'support',
      validation: (rule) => rule.min(2).max(6),
      of: [
        {
          type: 'object',
          name: 'supportPathway',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              rows: 3,
            }),
          ],
          preview: {
            select: {
              title: 'title',
              subtitle: 'description',
            },
          },
        },
      ],
    }),

    defineField({
      name: 'printsSectionTitle',
      title: 'Prints section title',
      type: 'string',
      group: 'prints',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'printsSectionIntro',
      title: 'Prints section intro',
      type: 'text',
      rows: 3,
      group: 'prints',
    }),
    defineField({
      name: 'featuredPrintImage',
      title: 'Featured print banner image',
      type: 'image',
      group: 'prints',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Alt text', type: 'string' })],
    }),
    defineField({
      name: 'featuredPrintKicker',
      title: 'Featured print kicker',
      type: 'string',
      group: 'prints',
    }),
    defineField({
      name: 'featuredPrintTitle',
      title: 'Featured print title',
      type: 'string',
      group: 'prints',
    }),
    defineField({
      name: 'featuredPrintBody',
      title: 'Featured print text',
      type: 'text',
      rows: 3,
      group: 'prints',
    }),
    defineField({
      name: 'featuredPrintCtaLabel',
      title: 'Featured print button label',
      type: 'string',
      group: 'prints',
    }),
    defineField({
      name: 'featuredPrintCtaLink',
      title: 'Featured print button link',
      type: 'string',
      group: 'prints',
      description: 'Use a URL, or #contact for on-page link.',
    }),
    defineField({
      name: 'printCards',
      title: 'Print cards',
      type: 'array',
      group: 'prints',
      validation: (rule) => rule.min(2).max(12),
      of: [
        {
          type: 'object',
          name: 'printCard',
          fields: [
            defineField({
              name: 'image',
              title: 'Image',
              type: 'image',
              options: { hotspot: true },
              validation: (rule) => rule.required(),
              fields: [defineField({ name: 'alt', title: 'Alt text', type: 'string' })],
            }),
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              validation: (rule) => rule.required(),
            }),
            defineField({ name: 'artist', title: 'Artist', type: 'string' }),
            defineField({
              name: 'year',
              title: 'Year',
              type: 'number',
              validation: (rule) => rule.min(1000).max(2100),
            }),
            defineField({ name: 'priceLabel', title: 'Price label', type: 'string' }),
            defineField({ name: 'availability', title: 'Availability note', type: 'string' }),
            defineField({
              name: 'ctaLabel',
              title: 'Button label',
              type: 'string',
              initialValue: 'Buy print',
            }),
            defineField({
              name: 'purchaseUrl',
              title: 'Purchase URL',
              type: 'url',
              description: 'Direct shop/checkout link.',
            }),
            defineField({
              name: 'linkedExhibition',
              title: 'Linked gallery exhibition',
              type: 'reference',
              to: [{ type: 'galleryExhibition' }],
              description: 'Optional alternative to purchase URL.',
            }),
          ],
          preview: {
            select: {
              title: 'title',
              subtitle: 'artist',
              media: 'image',
            },
          },
        },
      ],
    }),

    defineField({
      name: 'contactSectionTitle',
      title: 'Contact section title',
      type: 'string',
      group: 'contact',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'contactSectionIntro',
      title: 'Contact section intro',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact email',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactPhone',
      title: 'Contact phone',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactNote',
      title: 'Contact note',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'formSubmitLabel',
      title: 'Form submit button label',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'formSuccessMessage',
      title: 'Form success message',
      type: 'string',
      group: 'contact',
    }),
  ],
})
